---
layout: cv
title: Resume
---
# Nickolas Kirby

**Phone:** (208) 569-1914  
**Email:** [nickolas.kirby14@gmail.com](mailto:nickolas.kirby14@gmail.com)  
**LinkedIn:** [linkedin.com/in/nickolas-k-a0a962210](https://www.linkedin.com/in/nickolas-k-a0a962210)

---

## **Objective**

Upcoming Accounting graduate aspiring to become a CPA, eager to apply my strong foundation in accounting principles, data science, and analytical skills to contribute effectively in an entry-level role.

---

## **Education**

**Bachelor of Science in Accounting**  
*Brigham Young University - Idaho, Rexburg, Idaho*  
**Sep 2020 - Dec 2024**

- Major in Accounting
- Certificate of Data Science
- Relevant coursework: Financial Accounting, Cost Accounting, Tax Accounting, Accounting Information Systems, Advanced Spreadsheet Application, Data Science Programming, Business Analytics

---

## **Experience**

### **Route Coordinator / Delivery Specialist**  
*Rexburg Floral, Rexburg, Idaho*  
**Sep 2022 - Present**

- Managed cargo handling, ensured order fulfillment, and resolved issues related to the distribution of deliveries.
- Developed comprehensive order sheets and refined route directions to enhance efficiency and timeliness of deliveries.

### **Staff Accounting Intern**  
*Melaleuca: The Wellness Company, Idaho Falls, Idaho*  
**Sep 2023 - Jan 2024**

- Prepared financial statements and assisted with internal auditing for the company's foreign division, while also conducting special projects involving research, coordination, and information gathering.
- Reviewed and analyzed departmental variances monthly to identify material differences, and prepared closing journal entries to address any discrepancies or errors.

### **Accounting / Accounts Payable Intern**  
*Yellowstone Plastics, Idaho Falls, Idaho*  
**Jul 2023 - Sep 2023**

- Promoted from "Business Operations Intern" at a sister company into a specialized "Accounting Intern" by exceeding expectations and displaying exceptional knowledge regarding accounting systems and scenarios.
- Led and analyzed with the accounting manager regarding: Chart of accounts, Financial Statements, Cash Flow Projection, Petty Cash Reconciliation, Account Reconciliations, Month-End Entries, Accounts Payable, Cycle Counting/Inventory Management.

### **Business Operations Intern**  
*Volm Companies, Idaho Falls, Idaho*  
**Jun 2023 - Sep 2023**

- Received hands-on experience working in a variety of departments including Purchasing, Production, Finance, Sales, Inventory Control, Human Resources, Safety, IT, Transportation, Logistics, Marketing, and Equipment.
- Acquired comprehensive understanding of end-to-end business operations, encompassing workflow, processes, and product delivery throughout various departments.

### **Shift Lead**  
*Pick Me Up Drinks, Idaho Falls, Rigby, Rexburg, Idaho*  
**Sep 2020 - Sep 2022**

- Remained at the top of sales while managing inventory, cashiering, credit card processing, and money handling along with miscellaneous tasks.
- Executed opening and closing procedures, monitored employee workflow, and fostered team collaboration to ensure smooth operations at the location.

---

## **Skills**

- **Software & Tools:** Infor CloudSuite ERP Cloud System, J.D. Edwards, Data Access Studio, SAGE, Microsoft Excel, Microsoft Word, Microsoft Power BI, Tableau
- **Other Skills:** Supervising, Problem Solving, Business Development, Communication, Teamwork, Inventory, Time Management

<!-- ### Footer

Last updated: December 14, 2024 -->